#!/bin/bash

# Install Script for Arch Linux
# Forked from Dasgeekchannel AutoInstallBashScripts
# Version 1.0.0

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
else
  # Update and Upgrade
  echo "Updating and Upgrading"
  pacman -Syu --noconfirm

  pacman -S dialog --noconfirm
	cmd=(dialog --title "Shane Milton Photography Installer" --separate-output --checklist "Please Select Software You Want To Install:" 22 80 16)
	options=(
    #A "<----Category: Photography Software---->" on
        1_edit "    Darktable" off
        2_edit "    Gimp" off
        3_edit "    Krita" off
        4_edit "    Gimp-Plugin-Gmic" off
        5_edit "    Krita-Plugin-Gmic" off
        6_edit "    Digikam" off
        7_edit "    Hugin" off
        8_edit "    Displaycal (Monitor Calibration)" off
        9_edit "    Geeqie (Color Managed Image Viewer)" off
    #B "<----Category: Video Software"
        1_video "   Vlc" off
        2_video "   OBS-Studio" off
        3_video "   Kdenlive (Video Editor W/Plugins)" off
        4_video "   Blender" off
    )
    choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
    clear
    for choice in $choices
    do
      case $choice in

# Section A ----Photography Software----

    1_edit)
        # Install Darktable
        echo "Installing Darktable RAW Editor"
        pacman -S darktable --noconfirm
        ;;

    2_edit)
        # Install Gimp
        echo "Installing Gimp Image Editor"
        pacman -S gimp --noconfirm
        ;;

    3_edit)
        # Install krita
        echo "Installing Krita"
        pacman -S krita --noconfirm
        ;;

    4_edit)
        # Install Gimp-Plugin-Gmic
        echo "Installing Gmic Gimp Plugin"
        pacman -S gimp-plugin-gmic --noconfirm
        ;;

    5_edit)
        # Install Krita-Plugin-Gmic
        echo "Installing Gmic Krita Plugin"
        pacman -S krita-plugin-gmic --noconfirm
        ;;

    6_edit)
        # Install Digikam
        echo "Installing Digikam"
        pacman -S digikam --noconfirm
        ;;

    7_edit)
        # Install Hugin
        echo "Installing Hugin"
        pacman -S hugin --noconfirm
        ;;

    8_edit)
        # Install Displaycal
        echo "Installing Displaycal"
        pacman -S displaycal --noconfirm
        ;;

    9_edit)
        # Install Geeqie
        echo "Installing Geeqie"
        pacman -S geeqie --noconfirm
        ;;

# Section B ----Video Software----

    1_video)
        # Install VLC
        echo "Installing VLC"
        pacman -S vlc --noconfirm
        ;;

    2_video)
        # Install OBS-Studio
        echo "Installing OBS-STUDIO"
        pacman -S obs-studio --noconfirm
        ;;

    3_video)
        # Install Kdenlive
        echo "Installing Kdenlive"
        pacman -S kdenlive --noconfirm
        pacman -S frei0r-plugins --noconfirm
        pacman -S breeze-icons --noconfirm
        ;;

    4_video)
        # Install Blender 3D
        echo "Installing Blender 3D"
        pacman -S blender --noconfirm
        ;;

      esac
  done
fi
