#!/bin/bash

# Install Script for Arch Linux
# Forked from Dasgeekchannel AutoInstallBashScripts
# Version 1.0.0

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
else
  # Update and Upgrade
  echo "Updating and Upgrading"
  pacman -Syu --noconfirm

  pacman -S dialog --noconfirm
	cmd=(dialog --title "Shane Milton Photography Installer" --separate-output --checklist "Please Select Software You Want To Install:" 22 80 16)
	options=(
    #A "<----Category: Photography Software---->" on
        1_edit "    Darktable" off
        2_edit "    Gimp" off
        3_edit "    Krita" off
        4_edit "    Gimp-Plugin-Gmic" off
        5_edit "    Krita-Plugin-Gmic" off
        6_edit "    Digikam" off
        7_edit "    Hugin" off
        8_edit "    Displaycal (Monitor Calibration)" off
        9_edit "    Geeqie (Color Managed Image Viewer)" off
       10_edit "    Colord-KDE (Colord Support for KDE)" off
    #B "<----Category: Video Software---->" on
        1_video "   Vlc" off
        2_video "   OBS-Studio" off
        3_video "   Kdenlive (Video Editor W/Plugins)" off
        4_video "   Blender" off
        5_video "   FFMPEG" off
    #C "<----Category: Audio Tools---->" on
        1_audio "   Audacity" off
        2_audio "   Ardour (DAW W/Video plugins)" off

    #D "<----Category: KDE Plasma Tools---->" on
        1_kde "     plasma-desktop" off
        2_kde "     KCM-Config" off
        3_kde "     KDE-GTk-Config" off
        4_kde "     breeze-gtk" off
        5_kde "     dolphin" off
        6_kde "     ark-for-zip" off
        7_kde "     plasma-nm" off
        8_kde "     plasma-pa" off
        9_kde "     plasma-browser-integration" off
        10_kde "     bluedevil" off
        11_kde "        kde-plasma-addons" off
        12_kde "        kgamma5" off
        13_kde "        kinfocenter" off
        14_kde "        kscreen" off
        15_kde "        ksshaskpass" off
        16_kde "        ksysguard" off
        17_kde "        kwrited" off
        18_kde "        oxygen" off
        19_kde "        plasma-wallpapers" off
        20_kde "        user-manager" off
        21_kde "        powerdevil" off
        22_kde "        xdg-desktop-kde" off
    )
    choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
    clear
    for choice in $choices
    do
      case $choice in

# Section A ----Photography Software----

    1_edit)
        # Install Darktable
        echo "Installing Darktable RAW Editor"
        pacman -S darktable --noconfirm
        ;;

    2_edit)
        # Install Gimp
        echo "Installing Gimp Image Editor"
        pacman -S gimp --noconfirm
        ;;

    3_edit)
        # Install krita
        echo "Installing Krita"
        pacman -S krita --noconfirm
        ;;

    4_edit)
        # Install Gimp-Plugin-Gmic
        echo "Installing Gmic Gimp Plugin"
        pacman -S gimp-plugin-gmic --noconfirm
        ;;

    5_edit)
        # Install Krita-Plugin-Gmic
        echo "Installing Gmic Krita Plugin"
        pacman -S krita-plugin-gmic --noconfirm
        ;;

    6_edit)
        # Install Digikam
        echo "Installing Digikam"
        pacman -S digikam --noconfirm
        ;;

    7_edit)
        # Install Hugin
        echo "Installing Hugin"
        pacman -S hugin --noconfirm
        ;;

    8_edit)
        # Install Displaycal
        echo "Installing Displaycal"
        pacman -S displaycal --noconfirm
        ;;

    9_edit)
        # Install Geeqie
        echo "Installing Geeqie"
        pacman -S geeqie --noconfirm
        ;;

    10_edit)
        # Install Colord-KDE
        echo "Installing Colord-KDE"
        pacman -S colord-kde --noconfirm
        ;;

# Section B ----Video Software----

    1_video)
        # Install VLC
        echo "Installing VLC"
        pacman -S vlc --noconfirm
        ;;

    2_video)
        # Install OBS-Studio
        echo "Installing OBS-STUDIO"
        pacman -S obs-studio --noconfirm
        ;;

    3_video)
        # Install Kdenlive
        echo "Installing Kdenlive"
        pacman -S kdenlive --noconfirm
        pacman -S frei0r-plugins --noconfirm
        pacman -S breeze-icons --noconfirm
        ;;

    4_video)
        # Install Blender 3D
        echo "Installing Blender 3D"
        pacman -S blender --noconfirm
        ;;

    5_video)
        # Install FFMPEG
        echo "Installing FFMPEG"
        pacman -S ffmpeg --noconfirm
        ;;

# Section C ----Audio Tools----

    1_audio)
        # Install Audacity
        echo Installing Audacity
        pacman -S audacity --noconfirm
        ;;

    2_audio)
        # Install Ardour
        echo "Installing Ardour"
        pacman -S ardour --noconfirm
        pacman -S harvid --noconfirm
        pacman -S xjadeo --noconfirm
        ;;

# Section D ----KDE Plasma Tools----
    1_kde)
        # Install Plasma Desktop
        echo "Installing Plasma-Desktop"
        pacman -S plasma-desktop --noconfirm
        ;;

    2_kde)
        # Install ssdm-kcm
        echo "Installing ssdm-kcm"
        pacman -S sddm-kcm --noconfirm
        ;;

    3_kde)
        # Install kde-gtk-config
        echo "Installing kde-gtk-config"
        pacman -S kde-gkt-config --noconfirm
        ;;

    4_kde)
        # Install breeze-gtk
        echo "Installing breeze-gtk"
        pacman -S breeze-gtk --noconfirm
        ;;

    5_kde)
        # Install Dolphin File Manager
        echo "Installing dolphin"
        pacman -S dolphin --noconfirm
        ;;

    6_kde)
        # Install ark
        echo "Installing Ark"
        pacman -S ark --noconfirm
        ;;

    7_kde)
        # Install plasma-nm
        echo "Installing plasma-nm"
        pacman -S plasma-nm --noconfirm
        ;;

    8_kde)
        # Install plasma-pa
        pacman -S plasma-pa --noconfirm
        ;;

    9_kde)
        # Install plasma-browser-integration
        pacman -S plasma-browser-integration --noconfirm
        ;;

    10_kde)
        # Install bluedevil
        pacman -S bluedevil --noconfirm
        ;;

    11_kde)
        # Install kdeplasma-addons
        pacman -S kdeplasma-addons --noconfirm
        ;;

    12_kde)
        # Install kgamma5
        pacman -S kgamma5 --noconfirm
        ;;

    13_kde)
        # Install kinfocenter
        pacman -S kinfocenter --noconfirm
        ;;

    14_kde)
        # Install kscreen
        pacman -S kscreen --noconfirm
        ;;

    15_kde)
        # Install ksshaskpass
        pacman -S ksshaskpass --noconfirm
        ;;

    16_kde)
        # Install ksysguard
        pacman -S ksysguard --noconfirm
        ;;

    17_kde)
        # Install kwrited
        pacman -S kwrited --noconfirm
        ;;

    18_kde)
        # Install oxygen
        pacman -S oxygen --noconfirm
        ;;

    19_kde)
        # Install plasma wallpapers
        pacman -S plasma-workspace-wallpapers --noconfirm
        ;;

    20_kde)
        # Install user-manager
        pacman -S user-manager --noconfirm
        ;;

    21_kde)
        # Install powerdevil
        pacman -S powerdevil --noconfirm
        ;;

    22_kde)
        # Install xdg-desktop-portal-kde
        pacman -S xdg-desktop-portal-kde --noconfirm
        ;;

      esac
  done
fi
