#!/bin/bash
# Forked  respin respun forked stolen and modified by DasGeek
# Tested w/ Elementary OS Loki & Ubuntu 17 and 18.04 LTS 
# Forked and spooned from some forum post I can no longer find in a galaxy of the internet
# Thank you to BigDaddyLinux and Skrappjaw for contributing!
# Version 2.0.0

if [[ $EUID -ne 0 ]]; then
   	echo "This script must be run as root type: sudo ./installscript" 
   	exit 1
else
	#Update and Upgrade
	echo "Updating and Upgrading"
	apt-get update && sudo apt-get upgrade -y

	sudo apt-get install dialog 
	cmd=(dialog --title "DasGeek Installer" --separate-output --checklist "Please Select Software You Want To Install:" 22 80 16)
	options=(
		#A "<----Category: Software Repositories---->" on
			1_repos "	Install Flatpak Repository" off
		#B "<----Category: Notes---->" on 
	        1_notes "	Simplenote (SNAP)" off
	    #C "<----Category: Social---->" on
			1_social "	Mumble Client" off
	        2_social "	Zoom Meeting Client" off
	        3_social "	Telegram (Flatpak)" off
	        4_social "	Discord (Flatpak)" off
	    #D "<----Category: Tweaks---->" on
	        1_tweak "	Ubuntu Restricted Extras" off
	        2_tweak "	Gnome Tweak Tool" off
	    #E "<----Category: Media---->" on  
	        1_media "	Gnome Videos" off
	    #F "<----Category: Internet---->" on
	        1_internet "	Google Chrome" off
	    #G "<----Category: Video, Audio & Pic Editing---->" on
	        1_edit "	Kdenlive" off
	        2_edit "	Darktable" off
	        3_edit "	GIMP" off
	        4_edit "	OBS-Studio" off
	        5_edit "	Audacity" off
			6_edit "	Krita" off
			7_edit "	VLC" off
		
		#H "<----Category: Utility---->" on
			1_utility "	Synology NAS Backup" off
			2_utility "	Guvcview (webcam settings)" off
			3_utility "	Cheese" off	
		#I "<----Category: Coding & FTP---->" on
	    	1_coding "	Sublime Text" off # any option can be set to default to "on"
			2_coding "	Atom" off
			3_coding "	Visual Studio Code" off
	        4_coding "	Filezilla" off
		#J "<----Category: Gaming & Fun---->" on
			1_gaming "	Steam (Valve)" off
			2_gaming "	Lutris" off
			5_gaming "	Gnome Twitch Client (Flatpak)" off		
		L "Post Install Auto Clean Up & Update" off)
		choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
		clear
		for choice in $choices
		do
		    case $choice in
# Section A ------------repos----------------------
	        1_repos)	
				#Install Flatpak Repo (Software Repository)
				echo "Installing Flatpak Repository"
				add-apt-repository ppa:alexlarsson/Flatpak
				apt update && sudo apt install flatpak -y 
				apt install gnome-software-plugin-flatpak -y
				;;

			2_repos)
				#Flathub Repos for flatpak apps
				echo "Setting up Flathub Repo"
				flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
				;;
# Section B -------notes---------------------------

			1_notes)
			    #Simplenote (SNAP)
				echo "Installing Simplenote"
				snap install simplenote
				;;
# Section C --------social-------------------------

			1_social)
				#Mumble Client
				echo "Mumble"
				add-apt-repository ppa:mumble/release
				apt-get update
				apt-get install mumble -y
				;;		

			2_social)
				#Zoom
				echo "Installing Zoom Meeting Client"
				echo "Installing dependency first First"				
				apt install libxcb-xtest0 -y
				cd ~/Downloads		
				wget https://zoom.us/client/latest/zoom_amd64.deb
				sudo dpkg -i zoom_amd64.deb
				rm -rf zoom_amd64.deb
				;;
			3_social)
				#Telegram
				echo "Telegram (Flatpak)"
				flatpak install flathub org.telegram.desktop -y
				;;

			4_social)
				#Discord
				echo "Discord (Flatpak)"
				flatpak install flathub com.discordapp.Discord -y
				;;

# Section D -----------tweak-----------------------

			1_tweak)
				#Ubuntu Restricted Extras
				echo "Installing Ubuntu Restricted Extras"
				apt install ubuntu-restricted-extras -y
				;;
			
			2_tweak)
				#Gnome tweak tool
				echo "Installing Gnome Tweak Tool"
				apt install gnome-tweak-tool -y
				;;

# Section E -------------media---------------------

			1_media)
				#Gnome Videos (AKA Totem)
				echo "Installing Gnome Videos"
				apt install totem -y
				;;

# Section F -------------internet--------------------
			1_internet)
				#Chrome
				echo "Installing Google Chrome"
				wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
				sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
				apt-get update 
				apt-get install google-chrome-stable -y
				;;
	
# Section G -------------edit(Video/Audio/Pic)---------------------	
			1_edit)
				#Kdenlive
				echo "Kdenlive"
				apt-get install kdenlive -y
				apt-get install breeze-icon-theme -y
				;;
				
			2_edit)	
				#Darktable
				echo "Installing Darktable"
				sudo add-apt-repository ppa:pmjdebruijn/darktable-release
				apt update && sudo apt install darktable -y 
				;;            
    		
			3_edit)
				#GIMP
				echo "Installing GIMP"
				add-apt-repository ppa:otto-kesselgulasch/gimp
				apt update && sudo apt install gimp gimp-gmic -y 
				;;

			4_edit)
				#OBS Studio
				echo "Installing OBS Studio"
				add-apt-repository ppa:obsproject/obs-studio
 				apt-get update && sudo apt-get install obs-studio -y
				apt-get install ffmpeg -y
				;;	

			5_edit) 
				#Audacity
				echo "Installing Audacity"
				apt install audacity -y
				;;

			6_edit)
				#Krita
				echo "Installing Krita"
				add-apt-repository ppa:kritalime/ppa
				apt update && sudo apt install krita -y
				;;

			7_edit)
				#VLC
				echo "Installing VLC"
				apt install vlc -y
				;;

# Section H ----------utility------------------------	

			1_utility) 
				#Synology NAS Assistant & Backup
				echo "Installing Syn Assist, CloudStation Backup"
				wget -O synassistant.deb https://global.download.synology.com/download/Tools/Assistant/6.1-15163/Ubuntu/x86_64/synology-assistant_6.1-15163_amd64.deb
				sudo dpkg -i synassistant*.deb
				apt-get install -f -y
				rm -rf synassistant*.deb
				wget -O cloudback.deb https://global.download.synology.com/download/Tools/CloudStationBackup/4.2.6-4408/Ubuntu/Installer/x86_64/synology-cloud-station-backup-4408.x86_64.deb
				sudo dpkg -i cloudback*.deb
				apt-get install -f -y
				rm -rf cloudback*.deb
				;;

			2_utility) 
				#Guvcview
				echo "installing Guvcview"
				apt install libgsl2 -y
				apt install libguvcview-1.1-1 -y
				apt install guvcview -y
				;;

			3_utility) 
				#Cheese
				echo "Installing Cheese"
				apt install cheese -y
				;;

# Section I -----------coding-----------------------	

	        1_coding)
	            #Install Sublime Text*
				echo "Installing Sublime Text"
				wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
				sudo apt-get install apt-transport-https
				echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
				sudo apt update
				sudo apt install sublime-text -y
				;;

			2_coding)	
				#Atom
				echo "Installing Atom"				
				cd ~/Downloads			
				wget -O atom-amd64.deb https://atom.io/download/deb			
				dpkg -i atom-amd64.deb
				apt-get install -f -y
				rm -rf atom-amd64.deb
				apm install atom-html-preview
				;;

			3_coding)
				#Visual Studio Code
				echo "Visual Studio Code"
				wget -O visualstudio.deb https://go.microsoft.com/fwlink/?LinkID=760868
				dpkg -i visualstudio.deb
				;;
			
			4_coding)
				#Filezilla
				echo "Filezilla not related to Godzilla"
				apt install filezilla -y
				;;
			
# Section J -----------game-----------------------	
			1_gaming)
				#Steam
				echo "Installing Steam"				
				apt install steam -y
				;;

			2_gaming)
				#Lutris
				echo "Installing Lutris"
				ver=$(lsb_release -sr); if [ $ver != "17.10" -a $ver != "17.04" -a $ver != "16.04" ]; then ver=16.04; fi
				echo "deb http://download.opensuse.org/repositories/home:/strycore/xUbuntu_$ver/ ./" | sudo tee /etc/apt/sources.list.d/lutris.list
				wget -q http://download.opensuse.org/repositories/home:/strycore/xUbuntu_$ver/Release.key -O- | sudo apt-key add -
				sudo apt-get update
				sudo apt-get install lutris -y
				;;

			5_gaming) 
				#Gnome Twitch Client
				echo "installing Gnome Twitch"
				flatpak install flathub com.vinszent.GnomeTwitch -y
				;;
			
			L)  
				#Clean up
				echo "Running Clean Up And Update"
				sudo apt update
				sudo apt upgrade
				sudo apt-get autoremove
				;;
	
	    esac
	done
fi
